package com.xiaomi.factory.wifiadb.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xiaomi.factory.lib_db.entity.WifiSignal;

import com.xiaomi.factory.wifiadb.db.WifiSignalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wifiSignalDaoConfig;

    private final WifiSignalDao wifiSignalDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wifiSignalDaoConfig = daoConfigMap.get(WifiSignalDao.class).clone();
        wifiSignalDaoConfig.initIdentityScope(type);

        wifiSignalDao = new WifiSignalDao(wifiSignalDaoConfig, this);

        registerDao(WifiSignal.class, wifiSignalDao);
    }
    
    public void clear() {
        wifiSignalDaoConfig.clearIdentityScope();
    }

    public WifiSignalDao getWifiSignalDao() {
        return wifiSignalDao;
    }

}
